In [1]:
import numpy as np

## Basic


1 ----> 0_dim \n



N_dim -----> (N-1)_dim

In [26]:
data = np.array([
    [[3, 2], [8, 15]],
    [[5, 12], [21, 34]],
    [[3, 2], [8, 15]],
    [[5, 12], [21, 34]]
], dtype=np.int32)
data

array([[[ 3,  2],
        [ 8, 15]],

       [[ 5, 12],
        [21, 34]],

       [[ 3,  2],
        [ 8, 15]],

       [[ 5, 12],
        [21, 34]]], dtype=int32)

In [22]:
data.ndim

3

In [23]:
data.shape

(4, 2, 2)

In [27]:
data.dtype

dtype('int32')

In [28]:
data.itemsize

4

In [32]:
import sys

print("shape: ", data.shape)
print(f"item size: {data.itemsize} Byte")
print(f"size: {data.size} dooneh")
print(f"array in memmoory {data.size * data.itemsize} Byte")
print(f"{sys.getsizeof(data)}")

shape:  (4, 2, 2)
item size: 4 Byte
size: 16 dooneh
array in memmoory 64 Byte
208


## Slicing, Selection

In [33]:
my_arr = np.array([
    [[1, 2, 3], [5, 8, 32]], 
    [[2, 5, 12], [76, 12, 18]], 
    [[3, 3, 8], [54, 22, -21]]], 
dtype=np.int32)
my_arr

array([[[  1,   2,   3],
        [  5,   8,  32]],

       [[  2,   5,  12],
        [ 76,  12,  18]],

       [[  3,   3,   8],
        [ 54,  22, -21]]], dtype=int32)

In [34]:
my_arr.shape

(3, 2, 3)

In [35]:
my_arr[0, 1, 1]

np.int32(8)

In [37]:
my_arr[0, 0]

array([1, 2, 3], dtype=int32)

[4, 12, 21] ---> array[start:stop:step]

In [42]:
one_dim = np.array([10, 20 , 30 , 40, 50])
# one_dim[1:4]
# one_dim[:3]
# one_dim[2:]
# one_dim[2:]
# one_dim[::2]
one_dim[::-1]

array([50, 40, 30, 20, 10])

In [44]:
matrix = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15]
])
matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [45]:
matrix[:2, 1:3]

array([[2, 3],
       [7, 8]])

In [48]:
matrix[:, -1]

array([ 5, 10, 15])

In [51]:
matrix[::-1]

array([[11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5]])

## generate ndarray

In [57]:
my_arr = np.zeros((2, 3, 5), dtype=np.int8)

In [58]:
my_arr[0, 0, 1]= 12
my_arr

array([[[ 0, 12,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0]],

       [[ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0]]], dtype=int8)

In [59]:
np.zeros_like(my_arr)

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]], dtype=int8)

In [61]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [62]:
np.full((3, 4, 5), 20)

array([[[20, 20, 20, 20, 20],
        [20, 20, 20, 20, 20],
        [20, 20, 20, 20, 20],
        [20, 20, 20, 20, 20]],

       [[20, 20, 20, 20, 20],
        [20, 20, 20, 20, 20],
        [20, 20, 20, 20, 20],
        [20, 20, 20, 20, 20]],

       [[20, 20, 20, 20, 20],
        [20, 20, 20, 20, 20],
        [20, 20, 20, 20, 20],
        [20, 20, 20, 20, 20]]])

In [64]:
np.arange(10, 20, 2)

array([10, 12, 14, 16, 18])

In [71]:
range_example = np.arange(50).reshape(5, 10)
range_example.shape

(5, 10)

In [ ]:
for item in np.nditer(range_example):
    print(item)

In [ ]:
for indx, val in np.ndenumerate(range_example):
    print(indx, "---->", val)

In [79]:
example_arr = np.ones(10000).reshape(100, 100)

def f_loop():
    for item in np.nditer(example_arr):
        np.exp(item)
%timeit -n 10 f_loop()

5.89 ms ± 1.42 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [80]:
%timeit -n 10 np.exp(example_arr)

133 μs ± 55.1 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)


## masking

In [85]:
example_arr = np.arange(25).reshape(5, 5)
mask_example_arr = example_arr > 10
mask_example_arr

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [87]:
example_arr[example_arr % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [88]:
example_arr[example_arr > 20] = 0

In [89]:
example_arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20,  0,  0,  0,  0]])

## Broadcasting

In [91]:
arr = np.array([1, 2, 3])
result = arr * 2
result

array([2, 4, 6])

In [92]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]]) # shape (2, 3)
arr2 = np.array([1, 2, 3]) # shape (3,) ---> treated as (1, 3)

result = arr1 + arr2
result

array([[2, 4, 6],
       [5, 7, 9]])

In [93]:
arr1 = np.array([[1], [2], [3]]) # (3, 1)
arr2 = np.array([10, 20, 30]) # (3,) ---> treated as (1, 3)

result = arr1 * arr2
result

array([[10, 20, 30],
       [20, 40, 60],
       [30, 60, 90]])

In [94]:
arr1 = np.array([[1, 2], [3, 4]]) # (2, 2)
arr2 = np.array([10, 20, 30]) # (3,)

result = arr1 * arr2
result

ValueError: operands could not be broadcast together with shapes (2,2) (3,) 

## Math(ufunc)

In [95]:
angles = np.array([0, 30, 45, 60, 90])
radians = np.deg2rad(angles)


print("Sine values: ", np.sin(radians))
print("Cosine values: ", np.cos(radians))
print("Tangent values: ", np.tan(radians))

Sine values:  [0.         0.5        0.70710678 0.8660254  1.        ]
Cosine values:  [1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
Tangent values:  [0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


In [98]:
values = np.array([
    [1, 2], 
    [3, 4]
])

# np.exp(values)  # e ^ x
# np.log(values) # logarithm base e
np.log10(values)

array([[0.        , 0.30103   ],
       [0.47712125, 0.60205999]])

In [101]:
a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])

np.divide(a, b)  # a / b
np.power(a, b) # a ** b

array([     10,     400,   27000, 2560000])

In [106]:
data = np.array([5, 10, 15, 20, 25])

# np.sum(data)
# np.mean(data)
# np.median(data)
# np.std(data)
np.min(data)

np.int64(5)

In [112]:
arr = np.array([1.234, 5.678, 9.876, -2.3])

# np.round(arr, 2)
# np.floor(arr)
# np.ceil(arr)

np.clip(arr, 2, 8)

array([2.   , 5.678, 8.   , 2.   ])

## Random

In [119]:
np.random.rand(5)

array([0.64103419, 0.36577033, 0.82030792, 0.84013121, 0.56360948])

In [123]:
np.random.rand(2, 3, 4)

array([[[0.99182419, 0.21303631, 0.83988894, 0.44256737],
        [0.97141086, 0.76506422, 0.17160731, 0.91037282],
        [0.57490452, 0.02277357, 0.82444895, 0.05537136]],

       [[0.51497614, 0.29860495, 0.00969539, 0.59755999],
        [0.22821614, 0.90620541, 0.83408832, 0.91133483],
        [0.94055186, 0.4001401 , 0.72768567, 0.30651812]]])

In [130]:
np.random.randint(10, 50, size=(5, 12))

array([[34, 27, 17, 10, 23, 29, 32, 37, 43, 24, 39, 31],
       [46, 21, 27, 44, 31, 17, 11, 18, 26, 30, 34, 25],
       [32, 30, 10, 49, 33, 30, 39, 47, 29, 22, 48, 44],
       [41, 10, 16, 33, 29, 41, 15, 27, 17, 36, 49, 39],
       [25, 46, 21, 11, 13, 43, 21, 19, 43, 29, 43, 25]], dtype=int32)

In [134]:
numbers = [10, 20, 30, 40, 50]
np.random.choice(numbers)

np.int64(30)

In [139]:
np.random.choice(numbers, size=3, replace=False)

array([50, 40, 30])

In [145]:
np.random.shuffle(numbers)
print(numbers)

[30, 10, 20, 40, 50]


In [146]:
np.random.normal(loc=0, scale=1, size=10)

array([ 0.86135955, -1.64072864, -1.4442226 ,  1.37007331,  0.93238365,
        0.38487203, -1.24593644, -1.00282214,  1.53060081, -2.39356562])

In [147]:
np.random.uniform(low=5, high=15, size=10)

array([13.18160244,  8.14547576,  8.45494957,  9.68880372, 11.99132646,
       14.46486622, 12.90496527, 13.39874966, 13.82244707,  5.58462864])

In [152]:
np.random.binomial(n=10, p=0.5, size=10)

array([8, 3, 6, 5, 8, 3, 5, 3, 4, 5], dtype=int32)

In [163]:
np.random.seed(42)
np.random.normal(loc=0, scale=1, size=10)

array([ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986, -0.23415337,
       -0.23413696,  1.57921282,  0.76743473, -0.46947439,  0.54256004])

## Axis

In [165]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

sum_axis_0 = np.sum(arr, axis=0)
sum_axis_1 = np.sum(arr, axis=1)


print(f"Sum along axis 0 (column-wise): {sum_axis_0}")
print(f"Sum along axis 1 (row-wise): {sum_axis_1}")

Sum along axis 0 (column-wise): [12 15 18]
Sum along axis 1 (row-wise): [ 6 15 24]


In [166]:
np.max(arr, axis=0)

array([7, 8, 9])

In [169]:
np.cumsum(arr, axis=1)

array([[ 1,  3,  6],
       [ 4,  9, 15],
       [ 7, 15, 24]])

In [170]:
arr_3d = np.array([
    [[1, 2], [3, 4]], # Matrix 0
    [[5, 6], [7, 8]], # Matrix 1
    [[9, 10], [11, 12]], # Matrix 2
])

arr_3d.shape

(3, 2, 2)

In [171]:
np.sum(arr_3d, axis=0)

array([[15, 18],
       [21, 24]])

In [172]:
np.sum(arr_3d, axis=1)

array([[ 4,  6],
       [12, 14],
       [20, 22]])

In [173]:
np.sum(arr_3d, axis=2)

array([[ 3,  7],
       [11, 15],
       [19, 23]])

## reshape

In [179]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

arr.reshape(2, 4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [182]:
arr.reshape(2, -1,  4)

array([[[1, 2, 3, 4]],

       [[5, 6, 7, 8]]])

In [183]:
arr.reshape(-1)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [184]:
# image   (height, width, channel)
# batch images (batch, height, width, channel)

batch = np.random.rand(10, 64, 64, 3)
batch.shape

(10, 64, 64, 3)

In [186]:
batch.reshape(10, -1).shape

(10, 12288)

## concatenate, vstack, hstack

In [187]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

np.concatenate((arr1, arr2), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [189]:
np.vstack((arr1, arr2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [190]:
np.concatenate((arr1, arr2), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [191]:
np.hstack((arr1, arr2))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

## Vectorization

In [193]:
arr = np.array([1, 2, 3, 4, 5])

squared_loop = [x**2 for x in arr]
squared_vectorized = arr ** 2
squared_vectorized

array([ 1,  4,  9, 16, 25])

In [195]:
def custom_function(x):
    return x**2 if x%2==0 else x**3

arr = np.array([1, 2, 3, 4, 5])
vectorized_func = np.vectorize(custom_function)

vectorized_func(arr)

array([  1,   4,  27,  16, 125])

numpy.where function is a vectorized version of the ternary expression x if condition else y

In [198]:
a = np.arange(10).reshape(2, 5)
np.where( a > 4, a, a+3)

array([[3, 4, 5, 6, 7],
       [5, 6, 7, 8, 9]])

## Algebra

In [199]:
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[6, 23], [-1, 7], [8, 9]])

x @ y

array([[ 28,  64],
       [ 67, 181]])

In [201]:
np.linalg.inv(x@y) @ (x@y)

array([[ 1.00000000e+00, -2.40085729e-15],
       [-6.93889390e-18,  1.00000000e+00]])